[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker=clang"]
linker = "clang"

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "linker=clang", "-C", "link-arg=--target=aarch64-linux-gnu"]
linker = "clang"
